<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE AIRLINESYSTEM[
<!ELEMENT PIA (TITLE,DAY,FLIGHT,CAPTAIN,TIMMING,AIRPORT)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT DAY (#PCDATA)>
<!ELEMENT FLIGHT (#PCDATA)>
<!ELEMENT CAPTAIN (#PCDATA)>
<!ELEMENT TIMMING (#PCDATA)>
<!ATTLIST AIRPORT NAME CDATA "KARACHI AIRPORT">
<!ENTITY MN "MONDAY">
<!ENTITY TU "TUESDAY">
<!ENTITY WED "WEDNESDAY">
<!ENTITY TH "THURSDAY">
<!ELEMENT AIRBLUE (TITLE,DAY,FLIGHT,CAPTAIN,TIMMING,AIRPORT)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT DAY (#PCDATA)>
<!ELEMENT FLIGHT (#PCDATA)>
<!ELEMENT CAPTAIN (#PCDATA)>
<!ELEMENT TIMMING (#PCDATA)>

<!ELEMENT AIRSIAL (TITLE,DAY,FLIGHT,CAPTAIN,TIMMING,AIRPORT)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT DAY (#PCDATA)>
<!ELEMENT FLIGHT (#PCDATA)>
<!ELEMENT CAPTAIN (#PCDATA)>
<!ELEMENT TIMMING (#PCDATA)>


]>

<AIRLINESYSTEM>
    <PIA>
    <TITLE>PAKISTAN INTERNATIONAL AIRWAYS</TITLE>
    <DAY>&MN;</DAY>
    <FLIGHT>2340958700</FLIGHT>
    <CAPTAIN>SHER MUHAMMAD</CAPTAIN>
    <TIMMING>07:00 AM</TIMMING>
    <AIRPORT></AIRPORT>

    <DAY>&TU;</DAY>
    <FLIGHT>0495340968</FLIGHT>
    <CAPTAIN>WALI KHAN</CAPTAIN>
    <TIMMING>09:00 AM</TIMMING>
     <AIRPORT></AIRPORT>

    <DAY>&WED;</DAY>
    <FLIGHT>4857348534</FLIGHT>
    <CAPTAIN>ASAD KHAN</CAPTAIN>
    <TIMMING>07:00 PM</TIMMING>
     <AIRPORT></AIRPORT>
    </PIA>

    <AIRBLUE>
    <TITLE>AIRBLUE LIMITED</TITLE>
    <DAY>&MN;</DAY>
    <FLIGHT>4567895779</FLIGHT>
    <CAPTAIN>DANIYAL SHERAZI</CAPTAIN>
    <TIMMING>06:00 PM</TIMMING>
     <AIRPORT></AIRPORT>

    <DAY>&TU;</DAY>
    <FLIGHT>5946697867</FLIGHT>
    <CAPTAIN>ASAD SHAH</CAPTAIN>
    <TIMMING>11:00 AM</TIMMING>
     <AIRPORT></AIRPORT>

    <DAY>&WED;</DAY>
    <FLIGHT>2648698067</FLIGHT>
    <CAPTAIN>KHURRAM CHAKWAL</CAPTAIN>
    <TIMMING>10:30 PM</TIMMING>
     <AIRPORT></AIRPORT>

    <DAY>&TH;</DAY>
    <FLIGHT>37458696757</FLIGHT>
    <CAPTAIN>TAHMOOR MIRZA</CAPTAIN>
    <TIMMING>03:00 AM</TIMMING>
     <AIRPORT></AIRPORT>

    </AIRBLUE>

    <AIRSIAL>
    <TITLE>AIR SIAL</TITLE>
     <DAY>&MN;</DAY>
    <FLIGHT>47587696957</FLIGHT>
    <CAPTAIN>AHMED FARAZ</CAPTAIN>
    <TIMMING>08:00 PM</TIMMING>
     <AIRPORT></AIRPORT>

     <DAY>&TU;</DAY>
    <FLIGHT>2385756686</FLIGHT>
    <CAPTAIN>RASHID LATIF</CAPTAIN>
    <TIMMING>03:30 PM</TIMMING>
     <AIRPORT></AIRPORT>

     <DAY>&WED;</DAY>
    <FLIGHT>3857693645</FLIGHT>
    <CAPTAIN>ZARYAB KHAN</CAPTAIN>
    <TIMMING>01:00 PM</TIMMING>
     <AIRPORT></AIRPORT>

    </AIRSIAL>

</AIRLINESYSTEM>

